version: 2.1

aliases:
  - &on_master_after_test
    context: shardlabs
    filters:
      branches:
        only:
          - master
    requires:
      - test

jobs:
  test:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install development tools
          command: ./scripts/install_dev_tools.sh
      - run:
          name: Install dependencies
          command: ./scripts/install_dependencies.sh
      - run:
          name: Lint
          command: poetry run pylint starknet_devnet test
      - run:
          name: Setup example
          command: ./scripts/setup_example.sh
      - run:
          name: Run pytest tests
          command: poetry run pytest -s -vv test
  package_build_and_publish:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run: ./scripts/package_build_and_publish.sh
  image_build_and_push:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: ./scripts/image_build_and_push.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - package_build_and_publish:
          <<: *on_master_after_test
      - image_build_and_push:
          <<: *on_master_after_test
